# Generated by Django 3.1.7 on 2021-02-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210225_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='short_title',
        ),
        migrations.AddField(
            model_name='article',
            name='long_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='publication',
            field=models.CharField(default=1, max_length=150, verbose_name='published in: '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=150, verbose_name='author(s)'),
        ),
    ]
