# Generated by Django 3.1.7 on 2021-02-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210227_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
