# Generated by Django 3.1.7 on 2021-02-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210228_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='articles',
            new_name='article',
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
