# Generated by Django 3.1.7 on 2021-03-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
